name: ecommerce_sample
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  dotted_border: ^1.0.7
  flutter_svg: ^0.18.0

  http: ^0.12.1
  xs_progress_hud: ^1.0.2
  dio: ^3.0.10
  shared_preferences: ^0.5.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/